nguage: python
python:
  - "2.7"
# command to install dependencies
install: 
  - sudo pip install -r requirements.txt
  - sudo pip install -r test-requirements.txt
  - sudo pip install coverage
  - sudo pip install coveralls
# command to run tests
script: coverage run --source=opensearchsdk setup.py test
after_success: coveralls
